# -*- coding: utf-8 -*-
"""chroma_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDlR4b--mpXX15ik9AkqZ4GSHb7Y7mnf
"""

!pip install langchain chromadb openai tiktoken pypdf langchain_google_genai langchain_community



from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_community.vectorstores import Chroma

from langchain_core.documents import Document

doc1 = Document(
        page_content="Virat Kohli is one of the most successful and consistent batsmen in IPL history. Known for his aggressive batting style and fitness, he has led the Royal Challengers Bangalore in multiple seasons.",
        metadata={"team": "Royal Challengers Bangalore"}
    )
doc2 = Document(
        page_content="Rohit Sharma is the most successful captain in IPL history, leading Mumbai Indians to five titles. He's known for his calm demeanor and ability to play big innings under pressure.",
        metadata={"team": "Mumbai Indians"}
    )
doc3 = Document(
        page_content="MS Dhoni, famously known as Captain Cool, has led Chennai Super Kings to multiple IPL titles. His finishing skills, wicketkeeping, and leadership are legendary.",
        metadata={"team": "Chennai Super Kings"}
    )
doc4 = Document(
        page_content="Jasprit Bumrah is considered one of the best fast bowlers in T20 cricket. Playing for Mumbai Indians, he is known for his yorkers and death-over expertise.",
        metadata={"team": "Mumbai Indians"}
    )
doc5 = Document(
        page_content="Ravindra Jadeja is a dynamic all-rounder who contributes with both bat and ball. Representing Chennai Super Kings, his quick fielding and match-winning performances make him a key player.",
        metadata={"team": "Chennai Super Kings"}
    )

docs = [doc1,doc2,doc3,doc4,doc5]

vector_store = Chroma(
    embedding_function=GoogleGenerativeAIEmbeddings(model='models/gemini-embedding-001'),
    persist_directory="chroma_db",
    collection_name='sample'
)

# Used to securely store your API key
from google.colab import userdata

# Get the API key from Colab's secrets manager
GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')

# You can also set it as an environment variable (optional, but good practice for some libraries)
import os
os.environ['GOOGLE_API_KEY'] = GOOGLE_API_KEY

print("GOOGLE_API_KEY loaded and set.")

vector_store.add_documents(docs)

import google.generativeai as genai
import os

# Ensure your GOOGLE_API_KEY is set
if 'GOOGLE_API_KEY' not in os.environ:
    print('Please set your GOOGLE_API_KEY environment variable.')
else:
    for m in genai.list_models():
        if 'embedContent' in m.supported_generation_methods:
            print(m.name)

vector_store.get(include=['embeddings','documents','metadatas'])

vector_store.similarity_search(query='Who among these are a bolwer ?',k=2)

vector_store.similarity_search_with_score(query='Who among these are a bolwer ?',k=2)

vector_store.similarity_search_with_score(query='Players from Chennai Super Kings',filter={'team':'Chennai Super Kings'})

